version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-api
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LvSagrado@12345
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./azurite_data:/data
    command: "azurite --tableHost 0.0.0.0 --location /data --debug /data/debug.log"

volumes:
  sqlserver_data: