version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-api
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LvSagrado@12345
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  apikey.crudes:
    build:
      context: ./APIKEY.Crudes
    container_name: apikey-crudes
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=crudesDb;User=sa;Password=LvSagrado@12345;TrustServerCertificate=True
    ports:
      - "5000:80"
    depends_on:
      - sqlserver

  apigateway:
    build:
      context: ./APIGateway
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7071:80"
    depends_on:
      - apikey.crudes

volumes:
  sqlserver_data: